title: Poetry Archive
description: Poems by Phoenix and AIs, preserved in time.
url: "https://whobyphoenix.com"
baseurl: ""

kramdown:
  hard_wrap: true

collections:
  poems:
    output: false
  authors:
    output: false
  books:
    output: true
    permalink: /books/:name/

defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"

plugins:
  - jekyll-sitemap

exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - README.md
